// https://www.behance.net/search/projects?search=cyberpunk+website+design
// https://dribbble.com/shots/9954664-Cyberpunk-2145-Online-Resume
// https://www.reddit.com/r/LowSodiumCyberpunk/comments/n387d5/cyberpunk_inspired_android_theme_by_uouttiefive/
// https://www.behance.net/gallery/162458515/UXUI-design-Neural-networks-curator-corpo-website?tracking_source=search_projects%7Ccyberpunk+website+design

import 'augmented-ui'
import clsx from 'clsx'
import Head from 'next/head'
import Bio from '../components/bio.js'
import Icon from '../components/icon.js'
import Panel from '../components/panel.js'
import Projects from '../components/projects.js'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rowan&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.window}>
          <div className={clsx(styles['space-below'], "row flex-space-between")}>
            <Bio className={styles.bio} name="Rowan James" title="Profession: Developer" icon="/Flf8rd5WYAAJ8OU.jpg"></Bio>
            <Panel className={styles.network} title="Other Connections Found">
              <Icon alt="Github icon" image="github-mark-white.svg" text="Github" url="https://github.com" />
              <Icon alt="Email icon" image="mail.svg" text="Email" url="mailto:rowan.james.dev@gmail.com" />
            </Panel>
          </div>

          <div>
            <Projects />
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}
